runtime:
  sample_mode: false
  sample_row_limit: null

spark:
  app_name_prefix: anti-scraping-ec2
  master: local[*]
  shuffle_partitions: 32
  driver_memory: 8g
  executor_memory: 8g
  default_parallelism: 8

paths:
  base_uri: s3a://anti-scraping-soomin/anti-scraping
  raw_text_input: /opt/anti-scraping/data/access.log
  ip_hostname_lookup: /home/ubuntu/anti-scraping-detection-pipeline/sample_data/ip_hostname_lookup.csv